import React, { useEffect, useState } from "react";
import {
    Alert,
    ScrollView,
    StyleSheet,
    Text,
    View,
    TouchableOpacity,
} from "react-native";
import QRCode from "react-native-qrcode-svg";
import { useRouter } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import qrcode from "qrcode-generator";

import { apiRequest } from "../services/api";
import { getToken } from "../services/auth";
import { API_BASE_URL } from "../constants/config";

type CertificateData = {
    certificateId: string;
    participantName: string;
    moduleId: string;
    moduleName?: string;
    score: number;
    issuedAt?: string;
    verificationHash?: string;
};

function generateQrSvg(value: string) {
    const qr = qrcode(0, "M");

    qr.addData(value);
    qr.make();

    return qr.createSvgTag(4, 0);
}

export default function CertificateScreen() {
    const router = useRouter();

    const [loading, setLoading] = useState(true);
    const [certificate, setCertificate] =
        useState<CertificateData | null>(null);
    const [error, setError] = useState("");

    useEffect(() => {
        generateCertificate();
    }, []);


    const generateCertificate = async () => {
        try {
            setLoading(true);
            setError("");

            const token = await getToken();

            if (!token) {
                throw new Error("Please login again.");
            }



            const historyResponse = await apiRequest(
                "/api/training/history",
                {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                }
            );

            const history =
                historyResponse?.results ||
                historyResponse?.data ||
                historyResponse?.history ||
                [];

            if (!history.length) {
                throw new Error(
                    "No training result found. Please complete the assessment first."
                );
            }

            const latestResult = history[0];

            const moduleId =
                latestResult.module_id ||
                latestResult.moduleId;

            if (!moduleId) {
                throw new Error("Training module not found.");
            }



            const response = await apiRequest(
                "/api/certificates",
                {
                    method: "POST",

                    headers: {
                        Authorization: `Bearer ${token}`,
                    },

                    body: JSON.stringify({
                        moduleId,
                    }),
                }
            );

            const raw =
                response?.certificate ||
                response?.data ||
                response;

            const certId = raw?.certificateId || raw?.certificate_id;

            if (!certId) {
                throw new Error(
                    "Certificate was not generated by the server."
                );
            }

            const certificateData: CertificateData = {
                certificateId: certId,
                participantName:
                    raw?.participantName ||
                    raw?.worker_name ||
                    "Mining Safety Trainee",
                moduleId:
                    raw?.moduleId ||
                    raw?.module_code ||
                    String(raw?.module_id || moduleId),
                moduleName:
                    raw?.moduleName ||
                    raw?.module_title ||
                    "Fire & Explosion Response",
                score: Number(raw?.score ?? latestResult.score ?? 0),
                issuedAt: raw?.issuedAt || raw?.issued_at,
                verificationHash: raw?.verificationHash || raw?.verification_hash,
            };

            setCertificate(certificateData);
        } catch (err: any) {
            console.error(
                "Certificate generation error:",
                err
            );

            setError(
                err?.message ||
                "Unable to generate certificate."
            );
        } finally {
            setLoading(false);
        }
    };



    if (loading) {
        return (
            <View style={styles.center}>
                <Text style={styles.loading}>
                    Generating certificate...
                </Text>

                <Text style={styles.loadingSubtext}>
                    Verifying your training result
                </Text>
            </View>
        );
    }



    if (error || !certificate) {
        return (
            <View style={styles.center}>
                <Text style={styles.errorTitle}>
                    Certificate Unavailable
                </Text>

                <Text style={styles.error}>
                    {error ||
                        "Certificate information could not be loaded."}
                </Text>

                <TouchableOpacity
                    style={styles.button}
                    onPress={() => router.back()}
                >
                    <Text style={styles.buttonText}>
                        Go Back
                    </Text>
                </TouchableOpacity>
            </View>
        );
    }





    const certificateId =
        certificate.certificateId;

    const participantName =
        certificate.participantName ||
        "Participant";

    const score = Number(certificate.score || 0);

    const moduleName =
        certificate.moduleName ||
        (certificate.moduleId === "FIRE_01"
            ? "Fire & Explosion Response"
            : certificate.moduleId === "GAS_01"
                ? "Gas Leak & Confined Space Protocol"
                : certificate.moduleId);

    const issuedDate = certificate.issuedAt
        ? new Date(
            certificate.issuedAt
        ).toLocaleDateString("en-IN", {
            day: "2-digit",
            month: "long",
            year: "numeric",
        })
        : new Date().toLocaleDateString("en-IN", {
            day: "2-digit",
            month: "long",
            year: "numeric",
        });



    const verificationUrl =
        `${API_BASE_URL}/api/certificates/verify/${certificateId}`;


    const generatePDF = async () => {
        try {
            const qrSvg =
                generateQrSvg(verificationUrl);


            const escapeHtml = (value: string) =>
                value
                    .replace(/&/g, "&amp;")
                    .replace(/</g, "&lt;")
                    .replace(/>/g, "&gt;")
                    .replace(/"/g, "&quot;")
                    .replace(/'/g, "&#039;");

            const safeName =
                escapeHtml(participantName);

            const safeModule =
                escapeHtml(moduleName);

            const safeCertificateId =
                escapeHtml(certificateId);

            const safeIssuedDate =
                escapeHtml(issuedDate);

            const html = `
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8" />

<style>

@page {
    size: A4 landscape;
    margin: 0;
}

* {
    box-sizing: border-box;
}

html,
body {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
}

body {
    font-family: Arial, Helvetica, sans-serif;
    background: #eeeeee;
}

.certificate {

    width: 100%;
    height: 100vh;

    position: relative;

    background: #ffffff;

    border: 12px solid #f59e0b;

    padding: 42px 55px;

    text-align: center;

}

.inner-border {

    position: absolute;

    top: 18px;
    left: 18px;
    right: 18px;
    bottom: 18px;

    border: 1px solid #d1d5db;

    pointer-events: none;

}

.brand {

    margin-top: 5px;

    font-size: 30px;

    font-weight: 900;

    letter-spacing: 8px;

    color: #111827;

}

.government {

    margin-top: 6px;

    font-size: 13px;

    color: #6b7280;

}

.title {

    margin-top: 24px;

    font-size: 32px;

    font-weight: 800;

    letter-spacing: 1px;

    color: #111827;

}

.subtitle {

    margin-top: 7px;

    font-size: 14px;

    color: #6b7280;

}

.gold-line {

    width: 58%;

    height: 3px;

    margin: 20px auto;

    background: #f59e0b;

}

.presented {

    font-size: 14px;

    color: #6b7280;

}

.name {

    margin-top: 10px;

    font-size: 34px;

    font-weight: 700;

    color: #111827;

}

.name-line {

    width: 45%;

    height: 1px;

    background: #9ca3af;

    margin: 7px auto 15px auto;

}

.completed {

    font-size: 14px;

    color: #6b7280;

}

.module {

    margin-top: 10px;

    font-size: 22px;

    font-weight: 700;

    color: #374151;

}

.info-container {

    margin-top: 25px;

    display: flex;

    justify-content: center;

    gap: 100px;

}

.info-box {

    min-width: 120px;

}

.info-label {

    font-size: 10px;

    font-weight: 700;

    letter-spacing: 1px;

    color: #6b7280;

}

.info-value {

    margin-top: 5px;

    font-size: 19px;

    font-weight: 800;

    color: #111827;

}

.qr-container {

    position: absolute;

    right: 58px;

    bottom: 42px;

    width: 125px;

    text-align: center;

}

.qr-container svg {

    width: 105px;

    height: 105px;

}

.qr-label {

    margin-top: 4px;

    font-size: 9px;

    color: #6b7280;

}

.certificate-id {

    margin-top: 4px;

    font-size: 8px;

    font-weight: 700;

    color: #374151;

}

.footer {

    position: absolute;

    left: 0;

    right: 0;

    bottom: 22px;

    text-align: center;

    font-size: 9px;

    color: #6b7280;

}

.verified {

    position: absolute;

    left: 58px;

    bottom: 52px;

    font-size: 9px;

    color: #6b7280;

    text-align: left;

}

</style>

</head>

<body>

<div class="certificate">

    <div class="inner-border"></div>

    <div class="brand">
        DEEPVISION
    </div>

    <div class="government">
        GOVERNMENT OF JHARKHAND
    </div>

    <div class="title">
        CERTIFICATE OF COMPLETION
    </div>

    <div class="subtitle">
        AR-Based Industrial Safety Training
        • SIH26041
    </div>

    <div class="gold-line"></div>

    <div class="presented">
        This certificate is proudly presented to
    </div>

    <div class="name">
        ${safeName}
    </div>

    <div class="name-line"></div>

    <div class="completed">
        for successfully completing the training module
    </div>

    <div class="module">
        ${safeModule}
    </div>

    <div class="info-container">

        <div class="info-box">

            <div class="info-label">
                SCORE
            </div>

            <div class="info-value">
                ${score}%
            </div>

        </div>

        <div class="info-box">

            <div class="info-label">
                DATE OF ISSUE
            </div>

            <div class="info-value">
                ${safeIssuedDate}
            </div>

        </div>

    </div>

    <div class="verified">
        Digitally verifiable certificate
    </div>

    <div class="qr-container">

        ${qrSvg}

        <div class="qr-label">
            Scan to verify
        </div>

        <div class="certificate-id">
            ID: ${safeCertificateId}
        </div>

    </div>

    <div class="footer">
        DeepVision — AR-Based Industrial Safety Training
    </div>

</div>

</body>

</html>
`;


            // 1. Generate the PDF
            const { uri } = await Print.printToFileAsync({
                html,
                width: 842,
                height: 595,
            });

            console.log("Certificate PDF created:", uri);

            // 2. On Android (especially in Expo Go), Print.printToFileAsync writes to unscoped cache/Print/
            // which causes Sharing.shareAsync to fail with: "Not allowed to read file under given URL."
            // Copying the PDF to the scoped documentDirectory/cacheDirectory ensures the Android FileProvider has permission to share it.
            let shareableUri = uri;
            try {
                const baseDir =
                    FileSystem.documentDirectory || FileSystem.cacheDirectory;

                if (baseDir) {
                    const cleanId = safeCertificateId.replace(
                        /[^a-zA-Z0-9_-]/g,
                        "_"
                    );
                    const destUri = `${baseDir}DeepVision_Certificate_${cleanId}.pdf`;

                    await FileSystem.copyAsync({
                        from: uri,
                        to: destUri,
                    });

                    shareableUri = destUri;
                    console.log(
                        "Certificate copied to scoped storage:",
                        shareableUri
                    );
                }
            } catch (copyErr) {
                console.warn(
                    "Could not copy PDF to scoped directory, using original URI:",
                    copyErr
                );
            }

            // 3. Share the PDF using the system share sheet
            const sharingAvailable = await Sharing.isAvailableAsync();

            if (sharingAvailable) {
                try {
                    await Sharing.shareAsync(shareableUri, {
                        mimeType: "application/pdf",
                        dialogTitle: "DeepVision Safety Certificate",
                        UTI: "com.adobe.pdf",
                    });
                } catch (shareErr) {
                    console.warn(
                        "Sharing.shareAsync failed, falling back to system Print:",
                        shareErr
                    );
                    // Native Print dialog provides built-in "Save as PDF" / printer
                    await Print.printAsync({ uri });
                }
            } else {
                // On Web / desktop without share intent, open print / save dialog directly
                await Print.printAsync({ html });
            }
        } catch (err: any) {
            console.error("PDF generation error:", err);

            Alert.alert(
                "PDF Error",
                err?.message ||
                    "Unable to generate the certificate PDF. Please try again."
            );
        }
    };



    return (
        <ScrollView
            contentContainerStyle={
                styles.container
            }
        >
            <View style={styles.certificate}>

                <Text style={styles.brand}>
                    DEEPVISION
                </Text>

                <Text style={styles.government}>
                    GOVERNMENT OF JHARKHAND
                </Text>

                <Text style={styles.title}>
                    CERTIFICATE OF COMPLETION
                </Text>

                <Text style={styles.subtitle}>
                    AR-Based Industrial Safety Training
                    {" • "}
                    SIH26041
                </Text>

                <View style={styles.line} />

                <Text style={styles.label}>
                    This certificate is proudly
                    presented to
                </Text>

                <Text style={styles.name}>
                    {participantName}
                </Text>

                <Text style={styles.label}>
                    for successfully completing
                </Text>

                <Text style={styles.module}>
                    {moduleName}
                </Text>

                <View style={styles.infoRow}>

                    <View style={styles.infoBox}>
                        <Text style={styles.infoLabel}>
                            SCORE
                        </Text>

                        <Text style={styles.infoValue}>
                            {score}%
                        </Text>
                    </View>

                    <View style={styles.infoBox}>
                        <Text style={styles.infoLabel}>
                            DATE OF ISSUE
                        </Text>

                        <Text style={styles.infoValue}>
                            {issuedDate}
                        </Text>
                    </View>

                </View>

                <View style={styles.qrSection}>

                    <QRCode
                        value={
                            verificationUrl
                        }
                        size={120}
                        backgroundColor="white"
                        color="black"
                    />

                    <Text style={styles.qrText}>
                        Scan to verify certificate
                    </Text>

                    <Text
                        style={
                            styles.certificateId
                        }
                    >
                        ID: {certificateId}
                    </Text>

                </View>

                <Text style={styles.footer}>
                    DeepVision — AR-Based
                    Industrial Safety Training
                </Text>

            </View>

            <TouchableOpacity
                style={styles.button}
                onPress={generatePDF}
            >
                <Text style={styles.buttonText}>
                    Generate Certificate PDF
                </Text>
            </TouchableOpacity>

            <TouchableOpacity
                style={styles.secondaryButton}
                onPress={() =>
                    router.replace("/home")
                }
            >
                <Text
                    style={
                        styles.secondaryButtonText
                    }
                >
                    Back to Home
                </Text>
            </TouchableOpacity>

        </ScrollView>
    );
}

const styles = StyleSheet.create({

    container: {
        padding: 20,
        paddingBottom: 40,
        backgroundColor: "#f3f4f6",
        flexGrow: 1,
        alignItems: "center",
    },

    certificate: {
        width: "100%",
        maxWidth: 720,

        backgroundColor: "#ffffff",

        paddingVertical: 32,
        paddingHorizontal: 25,

        borderRadius: 16,

        borderWidth: 3,
        borderColor: "#f59e0b",

        alignItems: "center",

        position: "relative",
    },

    brand: {
        fontSize: 28,
        fontWeight: "900",
        letterSpacing: 5,
        color: "#111827",
    },

    government: {
        marginTop: 5,
        fontSize: 11,
        fontWeight: "600",
        color: "#6b7280",
        letterSpacing: 1,
    },

    title: {
        marginTop: 18,
        fontSize: 24,
        fontWeight: "800",
        textAlign: "center",
        color: "#111827",
    },

    subtitle: {
        marginTop: 6,
        color: "#6b7280",
        fontSize: 12,
        textAlign: "center",
    },

    line: {
        width: "75%",
        height: 2,
        backgroundColor: "#f59e0b",
        marginVertical: 20,
    },

    label: {
        color: "#6b7280",
        fontSize: 13,
        textAlign: "center",
    },

    name: {
        fontSize: 29,
        fontWeight: "800",
        marginVertical: 10,
        color: "#111827",
        textAlign: "center",
    },

    module: {
        fontSize: 20,
        fontWeight: "700",
        marginTop: 10,
        textAlign: "center",
        color: "#374151",
    },

    infoRow: {
        flexDirection: "row",
        justifyContent: "center",
        gap: 70,
        width: "100%",
        marginTop: 25,
    },

    infoBox: {
        alignItems: "center",
        minWidth: 110,
    },

    infoLabel: {
        fontSize: 10,
        fontWeight: "700",
        color: "#6b7280",
        textAlign: "center",
    },

    infoValue: {
        fontSize: 19,
        fontWeight: "800",
        color: "#111827",
        marginTop: 4,
        textAlign: "center",
    },

    qrSection: {
        marginTop: 25,
        alignItems: "center",
    },

    qrText: {
        marginTop: 8,
        fontSize: 11,
        color: "#6b7280",
    },

    certificateId: {
        marginTop: 4,
        fontSize: 10,
        fontWeight: "700",
        color: "#374151",
    },

    footer: {
        marginTop: 22,
        fontSize: 10,
        color: "#6b7280",
        textAlign: "center",
    },

    center: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 30,
        backgroundColor: "#f3f4f6",
    },

    loading: {
        fontSize: 19,
        fontWeight: "700",
        color: "#111827",
    },

    loadingSubtext: {
        marginTop: 8,
        fontSize: 13,
        color: "#6b7280",
    },

    errorTitle: {
        fontSize: 22,
        fontWeight: "800",
        color: "#111827",
        marginBottom: 10,
    },

    error: {
        color: "#dc2626",
        textAlign: "center",
        marginBottom: 20,
        fontSize: 14,
    },

    button: {
        marginTop: 22,
        backgroundColor: "#111827",
        paddingVertical: 15,
        paddingHorizontal: 28,
        borderRadius: 10,
        minWidth: 240,
        alignItems: "center",
    },

    buttonText: {
        color: "#ffffff",
        fontWeight: "700",
        fontSize: 15,
    },

    secondaryButton: {
        marginTop: 10,
        paddingVertical: 12,
        paddingHorizontal: 25,
    },

    secondaryButtonText: {
        color: "#374151",
        fontWeight: "600",
        fontSize: 14,
    },
});